name: Continuous Integration, Continuous Delivery Pipeline (GitHub Pages)

on:
  push:
    tags:
      - "v*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

  build:
    needs: install
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Type Checking
        run: pnpm run type-check

      - name: Run Build
        run: pnpm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist
